version: "3"
services:

  auth-db:  
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5433:5432

  product-db:  
    image: postgres:16
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5434:5432

  sales-db:  
    image: mongo:latest
    container_name: sales-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    ports:
      - 27017:27017
      - 28017:28017 

  sales_rabbit:  
    image: rabbitmq:3.12-management
    container_name: sales_rabbit
    ports:
      - 5672:5672 
      - 25676:25676 
      - 15672:15672  
