server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api

  datasource:
    url: jdbc:postgresql://localhost:5434/product-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: POSTGRESQL